ALTER TABLE PRODUCT
ADD CONSTRAINT fk_product_company 
FOREIGN KEY (inventory_id) 
REFERENCES INVENTORY(inventory_id)
ON DELETE CASCADE;

ALTER TABLE INVENTORY
ADD CONSTRAINT fk_inventory_product 
FOREIGN KEY (company_id) 
REFERENCES COMPANY(company_id)
ON DELETE CASCADE;

ALTER TABLE SALES
ADD CONSTRAINT fk_sales_product 
FOREIGN KEY (product_id) 
REFERENCES PRODUCT(product_id)
ON DELETE CASCADE;
